name: Setup

inputs:
  node-version:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{ inputs.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}

    - run: pnpm install
