name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22]

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm build

  lint:
    strategy:
      matrix:
        node-version: [22]

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm lint
